/*
  Phase 6F - the 4 templates' registry metadata (spec section 5's
  minimum field list). Pure data only - no renderer imports here, so
  this file can be read/tested independently of whether any template's
  actual HTML/PDF/DOCX implementation exists yet.
*/
import type { TemplateCapabilities } from "../contracts/types";

export const PROFESSIONAL_ATS_CAPABILITIES: TemplateCapabilities = {
  id: "professional-ats",
  name: "Professional ATS",
  description: "Single-column, ATS-first layout for corporate, legal, engineering, finance, and general office roles. No photo, minimal icons, fully linear reading order.",
  category: "ats",
  version: "1.0.0",
  status: "active",
  supportedFormats: ["html", "pdf", "docx"],
  supportedPaperSizes: ["letter", "a4"],
  supportedDensities: ["comfortable", "balanced", "compact"],
  atsLevel: "high",
  supportsPhoto: false,
  supportsSidebar: false,
  supportsMetricGrid: true,
  supportsHierarchy: true,
  supportsLanguages: false,
  supportsCustomSections: true,
  supportsMultiplePages: true,
  defaultPaperSize: "letter",
  defaultDensity: "comfortable",
  previewAsset: "/canonical-career/templates/previews/professional-ats.svg",
  renderer: "lib/resumeTemplates/templates/professionalAts/html.tsx",
  pdfRenderer: "lib/resumeTemplates/templates/professionalAts/pdf.ts",
  docxRenderer: "lib/resumeTemplates/templates/professionalAts/docx.ts",
  validationProfile: "professional-ats-wrapped-existing-pipeline",
};

export const MODERN_SIDEBAR_CAPABILITIES: TemplateCapabilities = {
  id: "modern-sidebar",
  name: "Modern Sidebar",
  description: "Two-column layout with a left identity/skills sidebar, for students, new grads, developers, designers, and portfolio-based applications.",
  category: "modern",
  version: "1.0.0",
  status: "active",
  supportedFormats: ["html", "pdf", "docx"],
  supportedPaperSizes: ["letter", "a4"],
  supportedDensities: ["comfortable", "balanced", "compact"],
  atsLevel: "medium",
  supportsPhoto: true,
  supportsSidebar: true,
  supportsMetricGrid: false,
  supportsHierarchy: true,
  supportsLanguages: true,
  supportsCustomSections: true,
  supportsMultiplePages: true,
  defaultPaperSize: "letter",
  defaultDensity: "balanced",
  previewAsset: "/canonical-career/templates/previews/modern-sidebar.svg",
  renderer: "lib/resumeTemplates/templates/modernSidebar/html.tsx",
  pdfRenderer: "lib/resumeTemplates/templates/modernSidebar/pdf.ts",
  docxRenderer: "lib/resumeTemplates/templates/modernSidebar/docx.ts",
  validationProfile: "sidebar-manifest-reading-order",
};

export const EXECUTIVE_MINIMAL_CAPABILITIES: TemplateCapabilities = {
  id: "executive-minimal",
  name: "Executive Minimal",
  description: "Single-column, wide-margin layout with strong name/title hierarchy and metric highlights, for executives, managers, consultants, and senior finance/R&D leaders.",
  category: "executive",
  version: "1.0.0",
  status: "active",
  supportedFormats: ["html", "pdf", "docx"],
  supportedPaperSizes: ["letter", "a4"],
  supportedDensities: ["spacious", "comfortable", "compact"],
  atsLevel: "high",
  supportsPhoto: false,
  supportsSidebar: false,
  supportsMetricGrid: true,
  supportsHierarchy: true,
  supportsLanguages: false,
  supportsCustomSections: true,
  supportsMultiplePages: true,
  defaultPaperSize: "letter",
  defaultDensity: "comfortable",
  previewAsset: "/canonical-career/templates/previews/executive-minimal.svg",
  renderer: "lib/resumeTemplates/templates/executiveMinimal/html.tsx",
  pdfRenderer: "lib/resumeTemplates/templates/executiveMinimal/pdf.ts",
  docxRenderer: "lib/resumeTemplates/templates/executiveMinimal/docx.ts",
  validationProfile: "executive-metric-grid-hierarchy",
};

export const CREATIVE_TIMELINE_CAPABILITIES: TemplateCapabilities = {
  id: "creative-timeline",
  name: "Creative Timeline",
  description: "Sidebar plus a vertical timeline for work/education history, for marketing, design, media, creative, and startup-oriented applications.",
  category: "creative",
  version: "1.0.0",
  status: "active",
  supportedFormats: ["html", "pdf", "docx"],
  supportedPaperSizes: ["letter", "a4"],
  supportedDensities: ["comfortable", "balanced", "compact"],
  atsLevel: "visual",
  supportsPhoto: true,
  supportsSidebar: true,
  supportsMetricGrid: false,
  supportsHierarchy: true,
  supportsLanguages: true,
  supportsCustomSections: true,
  supportsMultiplePages: true,
  defaultPaperSize: "letter",
  defaultDensity: "balanced",
  previewAsset: "/canonical-career/templates/previews/creative-timeline.svg",
  renderer: "lib/resumeTemplates/templates/creativeTimeline/html.tsx",
  pdfRenderer: "lib/resumeTemplates/templates/creativeTimeline/pdf.ts",
  docxRenderer: "lib/resumeTemplates/templates/creativeTimeline/docx.ts",
  validationProfile: "timeline-manifest-reading-order",
};

export const ALL_TEMPLATE_CAPABILITIES: TemplateCapabilities[] = [PROFESSIONAL_ATS_CAPABILITIES, MODERN_SIDEBAR_CAPABILITIES, EXECUTIVE_MINIMAL_CAPABILITIES, CREATIVE_TIMELINE_CAPABILITIES];
