/*
  Phase 6C gate test - individual mapper behavior. Run with
  `npx tsx lib/careerMemory/persistence/mappers.test.ts`. Replaces Phase
  6B's own version of this file (which only checked that every mapper
  threw MapperNotImplementedError) - that behavior is gone by design
  this round (mappers.ts's own header comment: "A future round (Phase
  6C)... is expected to replace every stub body below with a real
  implementation"), so this file now exercises the REAL mapper
  behavior, one function at a time, against the hand-authored fixture
  in testFixtures.ts. No mapper's expected value here was generated by
  running the mapper itself first.
*/
import {
  bySortOrderThenCreatedAt,
  canonicalRuntimeToInsertBundle,
  careerAwardRowToEntry,
  careerCredentialRowToEntry,
  careerExperienceRowToEntry,
  careerLanguageRowToRuntime,
  careerProfileRowToRuntime,
  careerProfileToCanonicalRuntime,
  careerProjectRowToEntry,
  careerPublicationRowToEntry,
  careerResumeVersionRowToRuntime,
  careerSourceDocumentRowToRuntimeSourceDocument,
  careerTailoredResumeRowToOverlayRecord,
  mapGeneratedDocumentToInsertInput,
  mapUserEditToInsertInput,
  runtimeToCareerAwardInsertInput,
  runtimeToCareerCredentialInsertInput,
  runtimeToCareerExperienceInsertInput,
  runtimeToCareerLanguageInsertInput,
  runtimeToCareerProfileInsertInput,
  runtimeToCareerProjectInsertInput,
  runtimeToCareerPublicationInsertInput,
  runtimeToCareerResumeVersionInsertInput,
  runtimeToCareerTailoredResumeInsertInput,
  runtimeSourceDocumentToInsertInput,
  sortByCreatedAtThenId,
} from "./mappers";
import type { CareerAwardRow, CareerCredentialRow, CareerExperienceRow, CareerProjectRow, CareerPublicationRow } from "./types";
import { buildFixtureResume, buildFixtureRuntime, trace } from "./testFixtures";
import { applyOverlay } from "../runtime/overlayRuntime";

let pass = 0;
let fail = 0;

function check(label: string, actual: unknown, expected: unknown) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  console.log(ok ? "PASS" : "FAIL", label, ok ? "" : `expected=${JSON.stringify(expected)} actual=${JSON.stringify(actual)}`);
  if (ok) pass++;
  else fail++;
}
function checkTrue(label: string, actual: boolean) {
  check(label, actual, true);
}

const runtime = buildFixtureRuntime();
const resume = runtime.resume;

// ==================== 1. Identity ====================
{
  const insertInput = runtimeToCareerProfileInsertInput("user-1", runtime);
  check("profile insert: user_id", insertInput.user_id, "user-1");
  check("profile insert: identity.fullName.value preserved verbatim (incl. accented chars)", (insertInput.identity as any).fullName.value, "JordanÉlan Lee");
  check("profile insert: identity.fullName.confidence preserved (jsonb, not reduced)", (insertInput.identity as any).fullName.confidence, 0.98);
  check("profile insert: identity.otherContactLines[0] preserved", (insertInput.identity as any).otherContactLines[0].value, "Montréal, QC • +1 (514) 555-0182");
  check("profile insert: schema_version from metadata", insertInput.schema_version, "resume-structured-v1");
  check("profile insert: serializer_version from metadata", insertInput.serializer_version, "career-memory-runtime-v1");

  const profileRow = { id: "profile-1", user_id: "user-1", identity: insertInput.identity!, summary_text: insertInput.summary_text!, preferences: {}, schema_version: insertInput.schema_version, serializer_version: insertInput.serializer_version, default_template_id: null, created_at: "x", updated_at: "x" };
  const slice = careerProfileRowToRuntime(profileRow);
  check("profile row->runtime: identity.fullName round-trips", slice.identity?.fullName?.value, "JordanÉlan Lee");
}

// ==================== 2. Summary ====================
{
  const insertInput = runtimeToCareerProfileInsertInput("user-1", runtime);
  check("profile insert: summary_text is professionalSummary.text", insertInput.summary_text, resume.professionalSummary!.text);
  const slice = careerProfileRowToRuntime({ id: "p", user_id: "u", identity: {}, summary_text: "Bilingual operations coordinator with 6+ years managing cross-functional logistics for mid-size manufacturers.", preferences: {}, schema_version: "s", serializer_version: "v", default_template_id: null, created_at: "x", updated_at: "x" });
  check("profile row->runtime: professionalSummaryText round-trips", slice.professionalSummaryText, resume.professionalSummary!.text);
}

// ==================== 3. Skills/groups/order ====================
{
  const insertInput = runtimeToCareerResumeVersionInsertInput("profile-1", runtime);
  const snapshot = insertInput.snapshot as any;
  check("resume version snapshot: skillGroups order preserved", snapshot.skillGroups.map((g: any) => g.skills[0]), ["Supply Chain", "Bilingüe (EN/FR)"]);
  check("resume version snapshot: skillGroups[0].label preserved", snapshot.skillGroups[0].label, "Core");
  check("resume version snapshot: skillGroups[1].label stays undefined-equivalent (dropped by JSON, not corrupted)", snapshot.skillGroups[1].label, undefined);
}

// ==================== 4. Flat experience ====================
{
  const flatEntry = resume.professionalExperience[1]; // exp-beta-analyst, no hierarchicalContent
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", flatEntry, { sourceDocumentId: "doc-1", sortOrder: 1 });
  check("experience insert: id preserved as own field", insertInput.id, "exp-beta-analyst");
  check("experience insert: organization reduced to .value", insertInput.organization, "Beta Logistics");
  check("experience insert: is_uncertain DIRECT from entry.isUncertain", insertInput.is_uncertain, true);
  check("experience insert: has_hierarchical_structure false for flat entry", insertInput.has_hierarchical_structure, false);
  check("experience insert: hierarchical_content empty for flat entry", insertInput.hierarchical_content, []);
  check("experience insert: sort_order from extra param", insertInput.sort_order, 1);
  checkTrue("experience insert: source_trace envelope carries entryId", (insertInput.source_trace as any).entryId === "exp-beta-analyst");
  check("experience insert: source_trace envelope carries reasonCodes", (insertInput.source_trace as any).reasonCodes, ["ambiguous-date-format"]);

  const row: CareerExperienceRow = { id: "db-uuid-1", profile_id: "profile-1", source_document_id: "doc-1", organization: insertInput.organization!, role: insertInput.role!, location: null, date_range_text: insertInput.date_range_text!, start_date_text: null, end_date_text: null, is_volunteer: false, content: insertInput.content as unknown[], hierarchical_content: [], has_hierarchical_structure: false, source_trace: insertInput.source_trace as any, confidence: null, is_uncertain: true, is_hidden: false, raw_header_text: insertInput.raw_header_text!, sort_order: 1, created_at: "x", updated_at: "x" };
  const reconstructed = careerExperienceRowToEntry(row);
  check("experience row->entry: entryId recovered from envelope (not DB uuid)", reconstructed.id, "exp-beta-analyst");
  check("experience row->entry: reasonCodes recovered from envelope", reconstructed.reasonCodes, ["ambiguous-date-format"]);
  check("experience row->entry: organization.value recovered", reconstructed.organization?.value, "Beta Logistics");
  check("experience row->entry: organization confidence uses documented fallback sentinel", reconstructed.organization?.extractionMethod, "fallback");
}

// ==================== 5. Hierarchical experience ====================
{
  const hierEntry = resume.professionalExperience[0]; // exp-acme-ops, has hierarchicalContent
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", hierEntry, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("experience insert: has_hierarchical_structure true", insertInput.has_hierarchical_structure, true);
  check("experience insert: hierarchical_content node id preserved", (insertInput.hierarchical_content as any)[0].id, "exp-acme-ops-h1");
  check("experience insert: hierarchical_content node depth preserved", (insertInput.hierarchical_content as any)[0].depth, 0);
  check("experience insert: hierarchical_content nested child id preserved", (insertInput.hierarchical_content as any)[0].children[0].id, "exp-acme-ops-h1-c1");
  check("experience insert: hierarchical_content nested child depth preserved", (insertInput.hierarchical_content as any)[0].children[0].depth, 1);
  check("experience insert: hierarchical_content numberingLabel preserved", (insertInput.hierarchical_content as any)[0].numberingLabel, "1.");

  const row: CareerExperienceRow = { id: "db-uuid-2", profile_id: "profile-1", source_document_id: "doc-1", organization: insertInput.organization!, role: insertInput.role!, location: insertInput.location!, date_range_text: insertInput.date_range_text!, start_date_text: insertInput.start_date_text!, end_date_text: insertInput.end_date_text!, is_volunteer: false, content: insertInput.content as unknown[], hierarchical_content: insertInput.hierarchical_content as unknown[], has_hierarchical_structure: true, source_trace: insertInput.source_trace as any, confidence: null, is_uncertain: false, is_hidden: false, raw_header_text: insertInput.raw_header_text!, sort_order: 0, created_at: "x", updated_at: "x" };
  const reconstructed = careerExperienceRowToEntry(row);
  check("experience row->entry: hierarchicalContent tree round-trips verbatim (opaque jsonb blob)", reconstructed.hierarchicalContent, hierEntry.hierarchicalContent);
}

// ==================== 6. Volunteer ====================
{
  const volEntry = resume.volunteerExperience[0];
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", volEntry, { sourceDocumentId: null, sortOrder: 0 });
  check("experience insert: is_volunteer true for volunteerExperience entry", insertInput.is_volunteer, true);
  check("experience insert: volunteer organization preserved", insertInput.organization, "Montréal Food Bank");
}

// ==================== 7. Education (snapshot-only, no child table) ====================
{
  const insertInput = runtimeToCareerResumeVersionInsertInput("profile-1", runtime);
  const snapshot = insertInput.snapshot as any;
  check("resume version snapshot: education array present (no child table exists)", snapshot.education.length, 1);
  check("resume version snapshot: education institution preserved", snapshot.education[0].institution.value, "McGill University");
}

// ==================== 8. Multiple credentials ====================
{
  const cred = resume.credentials[0];
  const insertInput = runtimeToCareerCredentialInsertInput("profile-1", cred, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("credential insert: kind DIRECT mapping", insertInput.kind, "certification");
  check("credential insert: name reduced to .value", insertInput.name, "Project Management Professional (PMP)");
  checkTrue("credential insert: source_trace envelope carries isUncertain (no dedicated column)", (insertInput.source_trace as any).isUncertain === false);

  const row2Input = runtimeToCareerCredentialInsertInput("profile-1", resume.credentials[1], { sourceDocumentId: "doc-1", sortOrder: 1 });
  check("credential insert (2nd, uncertain): kind license", row2Input.kind, "license");
  check("credential insert (2nd): source_trace envelope carries reasonCodes", (row2Input.source_trace as any).reasonCodes, ["low-confidence-header"]);

  const row: CareerCredentialRow = { id: "db-uuid-3", profile_id: "profile-1", source_document_id: "doc-1", name: insertInput.name!, issuer: insertInput.issuer!, credential_id: null, issue_date_text: insertInput.issue_date_text!, expiry_date_text: null, location: null, kind: "certification", details: [], source_trace: insertInput.source_trace as any, is_hidden: false, raw_header_text: insertInput.raw_header_text!, sort_order: 0, created_at: "x", updated_at: "x" };
  const reconstructed = careerCredentialRowToEntry(row);
  check("credential row->entry: entryId recovered", reconstructed.id, "cred-pmp");
  check("credential row->entry: names[] falls back to 1-item list from singular name", reconstructed.names[0]?.value, "Project Management Professional (PMP)");
  check("credential row->entry: isUncertain recovered from envelope", reconstructed.isUncertain, false);
}

// ==================== 9. Projects ====================
{
  const proj = resume.projects[0];
  const insertInput = runtimeToCareerProjectInsertInput("profile-1", proj, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("project insert: technologies[] preserves full StructuredTextValue (jsonb array column)", (insertInput.technologies as any)[0].confidence, 0.8);
  check("project insert: technologies[] value preserved", (insertInput.technologies as any)[0].value, "SAP S/4HANA");
  check("project insert: content[] preserved verbatim", (insertInput.content as any)[0].text, "Migrated legacy inventory system with zero downtime.");

  const row: CareerProjectRow = { id: "db-uuid-4", profile_id: "profile-1", source_document_id: "doc-1", name: insertInput.name!, role: insertInput.role!, date_range_text: insertInput.date_range_text!, technologies: insertInput.technologies as unknown[], content: insertInput.content as unknown[], source_trace: insertInput.source_trace as any, is_hidden: false, raw_header_text: insertInput.raw_header_text!, sort_order: 0, created_at: "x", updated_at: "x" };
  const reconstructed = careerProjectRowToEntry(row);
  check("project row->entry: technologies[] full object round-trips (jsonb, no reduction)", reconstructed.technologies, proj.technologies);
  check("project row->entry: entryId recovered", reconstructed.id, "proj-erp");
}

// ==================== 10. Awards ====================
{
  const award = resume.awards[0];
  const insertInput = runtimeToCareerAwardInsertInput("profile-1", award, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("award insert: name reduced to .value", insertInput.name, "Operations MVP 2021");
  const row: CareerAwardRow = { id: "db-uuid-5", profile_id: "profile-1", source_document_id: "doc-1", name: insertInput.name!, issuer: insertInput.issuer!, date_text: insertInput.date_text!, details: [], source_trace: insertInput.source_trace as any, is_hidden: false, raw_header_text: insertInput.raw_header_text!, sort_order: 0, created_at: "x", updated_at: "x" };
  const reconstructed = careerAwardRowToEntry(row);
  check("award row->entry: entryId recovered", reconstructed.id, "award-mvp");
  check("award row->entry: names[] falls back to 1-item list", reconstructed.names[0]?.value, "Operations MVP 2021");
}

// ==================== 11. Publications ====================
{
  const pub = resume.publications[0];
  const insertInput = runtimeToCareerPublicationInsertInput("profile-1", pub, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("publication insert: authors[] preserves full StructuredTextValue", (insertInput.authors as any)[0].value, "J. Lee");
  checkTrue("publication insert: long URL preserved without truncation", (insertInput.url_or_doi as string).length === pub.urlOrDoi!.value.length);
  check("publication insert: long URL exact match", insertInput.url_or_doi, pub.urlOrDoi!.value);

  const row: CareerPublicationRow = { id: "db-uuid-6", profile_id: "profile-1", source_document_id: "doc-1", title: insertInput.title!, authors: insertInput.authors as unknown[], publisher_or_venue: insertInput.publisher_or_venue!, date_text: insertInput.date_text!, url_or_doi: insertInput.url_or_doi!, details: [], source_trace: insertInput.source_trace as any, is_hidden: false, raw_header_text: insertInput.raw_header_text!, sort_order: 0, created_at: "x", updated_at: "x" };
  const reconstructed = careerPublicationRowToEntry(row);
  check("publication row->entry: entryId recovered", reconstructed.id, "pub-supplychain");
  check("publication row->entry: long URL round-trips exactly", reconstructed.urlOrDoi?.value, pub.urlOrDoi!.value);
  check("publication row->entry: authors[] round-trips full object", reconstructed.authors, pub.authors);
}

// ==================== 12. Custom sections (snapshot-only) ====================
{
  const insertInput = runtimeToCareerResumeVersionInsertInput("profile-1", runtime);
  const snapshot = insertInput.snapshot as any;
  check("resume version snapshot: customSections present", snapshot.customSections.length, 1);
  check("resume version snapshot: customSections originalHeading preserved (French)", snapshot.customSections[0].originalHeading, "Langues");
  check("resume version snapshot: customSections paragraph preserves accented text", snapshot.customSections[0].paragraphs[0].value, "Français (natif), Anglais (courant), Espagnol (intermédiaire)");
}

// ==================== 13. Metric grids (snapshot-only) ====================
{
  const insertInput = runtimeToCareerResumeVersionInsertInput("profile-1", runtime);
  const snapshot = insertInput.snapshot as any;
  check("resume version snapshot: metricGrids present", snapshot.metricGrids.length, 1);
  check("resume version snapshot: metricGrids entry value preserved", snapshot.metricGrids[0].entries[0].value.value, "32%");
  check("resume version snapshot: metricGrids columns preserved", snapshot.metricGrids[0].columns, 1);
}

// ==================== 14. SourceTrace ====================
{
  const entry = resume.professionalExperience[0];
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", entry, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("experience insert: source_trace.trace matches entry.source exactly", (insertInput.source_trace as any).trace, entry.source);
}

// ==================== 15. Confidence/uncertainty/reasonCodes ====================
{
  const entry = resume.professionalExperience[1]; // isUncertain: true, reasonCodes: ["ambiguous-date-format"]
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", entry, { sourceDocumentId: "doc-1", sortOrder: 1 });
  check("experience insert: entry-level confidence intentionally null (no natural aggregate - see snapshot)", insertInput.confidence, null);
  check("experience insert: is_uncertain DIRECT (real column exists)", insertInput.is_uncertain, true);

  const snapshot = runtimeToCareerResumeVersionInsertInput("profile-1", runtime).snapshot as any;
  check("resume version snapshot: per-field confidence fully preserved (organization)", snapshot.professionalExperience[0].organization.confidence, 0.95);
  check("resume version snapshot: per-field extractionMethod fully preserved (location, context-rule)", snapshot.professionalExperience[0].location.extractionMethod, "context-rule");
}

// ==================== 16. RawHeaderText ====================
{
  const entry = resume.professionalExperience[0];
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", entry, { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("experience insert: raw_header_text preserved verbatim", insertInput.raw_header_text, entry.rawHeaderText);
}

// ==================== 17. SourceDocuments ====================
{
  const doc = runtime.sourceDocuments[0];
  const runtimeDoc = careerSourceDocumentRowToRuntimeSourceDocument({ id: doc.id, profile_id: "profile-1", storage_bucket: "resume-sources", storage_path: "profile-1/doc-1/original.pdf", original_file_name: doc.fileName, mime_type: "application/pdf", byte_size: 1024, content_hash: doc.contentHash ?? null, parser_version: "pdf-parser-v3", file_type: doc.fileType, analysis_status: "succeeded", created_at: doc.addedAt, updated_at: doc.addedAt });
  check("source document row->runtime: id preserved", runtimeDoc.id, doc.id);
  check("source document row->runtime: fileName preserved", runtimeDoc.fileName, doc.fileName);
  check("source document row->runtime: contentHash preserved", runtimeDoc.contentHash, doc.contentHash);

  const insertInput = runtimeSourceDocumentToInsertInput("profile-1", doc, { storageBucket: "resume-sources", storagePath: "profile-1/doc-1/original.pdf", parserVersion: "pdf-parser-v3" });
  check("source document insert: file_type preserved", insertInput.file_type, doc.fileType);
  check("source document insert: content_hash preserved", insertInput.content_hash, doc.contentHash);
}

// ==================== 18. Version lineage ====================
{
  const insertInput = runtimeToCareerResumeVersionInsertInput("profile-1", runtime);
  check("resume version insert: id from runtime.version.id", insertInput.id, "version-1");
  check("resume version insert: reason preserved", insertInput.reason, "initial");
  check("resume version insert: parent_version_id null when absent", insertInput.parent_version_id, null);
  check("resume version insert: source_document_id is the latest sourceDocuments entry", insertInput.source_document_id, "doc-2");

  const row = { id: "version-1", profile_id: "profile-1", source_document_id: "doc-2", parent_version_id: null, reason: "initial" as const, snapshot: insertInput.snapshot, schema_version: insertInput.schema_version, serializer_version: insertInput.serializer_version, created_at: "2026-01-01T00:05:00.000Z", updated_at: "x" };
  const reconstructed = careerResumeVersionRowToRuntime(row);
  check("resume version row->runtime: resume round-trips via snapshot", reconstructed.resume, resume);
  check("resume version row->runtime: version.id preserved", reconstructed.version.id, "version-1");
}

// ==================== 19. Overlay ====================
{
  const record = runtime.overlayState.history[0];
  const insertInput = runtimeToCareerTailoredResumeInsertInput("profile-1", record, { applicationId: "app-1", resumeVersionId: "version-1", templateId: "classic", aiModel: "gpt-5.5", promptVersion: "package-v1" });
  check("tailored resume insert: application_id from extra param", insertInput.application_id, "app-1");
  check("tailored resume insert: overlay.appliedEntryIds preserved", (insertInput.overlay as any).appliedEntryIds, ["exp-acme-ops"]);
  check("tailored resume insert: overlay.overlay.professionalSummaryText preserved", (insertInput.overlay as any).overlay.professionalSummaryText, "Bilingual operations leader tailored for a supply-chain director role.");

  const row = { id: "tr-1", profile_id: "profile-1", application_id: "app-1", resume_version_id: "version-1", overlay: insertInput.overlay, template_id: "classic", ai_model: "gpt-5.5", prompt_version: "package-v1", created_at: "2026-01-06T00:00:00.000Z", updated_at: "x" };
  const reconstructed = careerTailoredResumeRowToOverlayRecord(row);
  check("tailored resume row->record: appliedEntryIds round-trips", reconstructed.appliedEntryIds, record.appliedEntryIds);
  check("tailored resume row->record: rejections round-trips", reconstructed.rejections, record.rejections);
  check("tailored resume row->record: overlay round-trips", reconstructed.overlay, record.overlay);
}

// ==================== 20. User edits ====================
{
  const insertInput = mapUserEditToInsertInput("profile-1", { targetTable: "career_experiences", targetId: "exp-1", fieldPath: "role", previousValue: "Coordinator", newValue: "Senior Coordinator", editedAt: "2026-01-07T00:00:00.000Z" });
  check("user edit insert: target_table preserved", insertInput.target_table, "career_experiences");
  check("user edit insert: previous_value preserved", insertInput.previous_value, "Coordinator");
  check("user edit insert: new_value preserved", insertInput.new_value, "Senior Coordinator");
  check("user edit insert: edited_at preserved", insertInput.edited_at, "2026-01-07T00:00:00.000Z");

  const nullEdit = mapUserEditToInsertInput("profile-1", { targetTable: "career_projects", targetId: "proj-1", fieldPath: "name" });
  check("user edit insert: previous_value defaults to null when omitted (not undefined)", nullEdit.previous_value, null);
}

// ==================== 21. Generated document metadata ====================
{
  const insertInput = mapGeneratedDocumentToInsertInput("tr-1", { storageBucket: "generated-resumes", storagePath: "profile-1/tr-1/resume.pdf", fileType: "pdf" });
  check("generated document insert: tailored_resume_id preserved", insertInput.tailored_resume_id, "tr-1");
  check("generated document insert: storage_path preserved", insertInput.storage_path, "profile-1/tr-1/resume.pdf");
  check("generated document insert: file_type preserved", insertInput.file_type, "pdf");
}

// ==================== 22. Null/undefined/empty ====================
{
  const minimalResume = buildFixtureResume();
  minimalResume.identity = undefined;
  minimalResume.professionalSummary = undefined;
  const minimalRuntime = { ...runtime, resume: minimalResume };
  const insertInput = runtimeToCareerProfileInsertInput("user-1", minimalRuntime);
  check("profile insert: identity defaults to {} when resume.identity is undefined (not null, not omitted)", insertInput.identity, {});
  check("profile insert: summary_text is null (not undefined, not empty string) when professionalSummary absent", insertInput.summary_text, null);

  const entryWithNoOrg = { ...resume.professionalExperience[1], organization: undefined };
  const entryInsert = runtimeToCareerExperienceInsertInput("profile-1", entryWithNoOrg, { sourceDocumentId: null, sortOrder: 0 });
  check("experience insert: undefined organization maps to null (never an empty string)", entryInsert.organization, null);

  const cleanEntryInsert = runtimeToCareerExperienceInsertInput("profile-1", resume.professionalExperience[0], { sourceDocumentId: null, sortOrder: 0 });
  check("experience insert: empty reasonCodes[] stays an empty array (not dropped, not omitted)", (cleanEntryInsert.source_trace as any).reasonCodes, []);

  const zeroConfidenceEntry = { ...resume.credentials[1] };
  const zeroInsert = runtimeToCareerCredentialInsertInput("profile-1", zeroConfidenceEntry, { sourceDocumentId: null, sortOrder: 0 });
  checkTrue("credential insert: false/0-like values are not coerced away (isUncertain: true preserved, not falsy-dropped)", (zeroInsert.source_trace as any).isUncertain === true);
}

// ==================== 23. Unicode/French accents ====================
{
  const insertInput = runtimeToCareerExperienceInsertInput("profile-1", resume.professionalExperience[0], { sourceDocumentId: "doc-1", sortOrder: 0 });
  check("experience insert: location with accented characters preserved exactly", insertInput.location, "Montréal, QC");
  const snapshot = runtimeToCareerResumeVersionInsertInput("profile-1", runtime).snapshot as any;
  check("resume version snapshot: identity.fullName accented chars preserved", snapshot.identity.fullName.value, "JordanÉlan Lee");
  check("resume version snapshot: customSections French text preserved exactly", snapshot.customSections[0].paragraphs[0].value, "Français (natif), Anglais (courant), Espagnol (intermédiaire)");
}

// ==================== 24. Long URLs ====================
{
  const pub = resume.publications[0];
  const insertInput = runtimeToCareerPublicationInsertInput("profile-1", pub, { sourceDocumentId: "doc-1", sortOrder: 0 });
  checkTrue("publication insert: long URL (200+ chars) not truncated", (insertInput.url_or_doi as string).length > 150);
  check("publication insert: long URL query string preserved exactly", insertInput.url_or_doi, pub.urlOrDoi!.value);
}

// ==================== 25. canonicalRuntimeToInsertBundle aggregate ====================
{
  const bundle = canonicalRuntimeToInsertBundle("user-1", "profile-1", runtime);
  check("insert bundle: experiences combines professional+volunteer in that order", bundle.experiences.map((e) => e.id), ["exp-acme-ops", "exp-beta-analyst", "exp-foodbank"]);
  check("insert bundle: experiences[2] (volunteer) is_volunteer true", bundle.experiences[2].is_volunteer, true);
  check("insert bundle: experiences sort_order matches array index", bundle.experiences.map((e) => e.sort_order), [0, 1, 2]);
  check("insert bundle: projects present", bundle.projects.length, 1);
  check("insert bundle: credentials present", bundle.credentials.length, 2);
  check("insert bundle: awards present", bundle.awards.length, 1);
  check("insert bundle: publications present", bundle.publications.length, 1);
  check("insert bundle: resumeVersion.snapshot is the full resume", bundle.resumeVersion.snapshot, resume);
}

// ==================== 26. Languages (Runtime-unsupported table) ====================
{
  const insertInput = runtimeToCareerLanguageInsertInput("profile-1", { name: "French", proficiency: "Native" }, 0);
  check("language insert: DTO name preserved (no Runtime source exists)", insertInput.name, "French");
  check("language insert: DTO proficiency preserved", insertInput.proficiency, "Native");
  const row = { id: "lang-1", profile_id: "profile-1", name: "French", proficiency: "Native", sort_order: 0, created_at: "x", updated_at: "x" };
  const dto = careerLanguageRowToRuntime(row);
  check("language row->dto: name round-trips", dto.name, "French");
}

// ==================== 27. Aggregate: careerProfileToCanonicalRuntime full bundle reconstruction ====================
{
  const bundle = {
    profile: { id: "profile-1", user_id: "user-1", identity: {}, summary_text: null, preferences: {}, schema_version: "resume-structured-v1", serializer_version: "career-memory-runtime-v1", default_template_id: null, created_at: "x", updated_at: "x" },
    sourceDocuments: [
      { id: "doc-1", profile_id: "profile-1", storage_bucket: "b", storage_path: "p1", original_file_name: "jordan-lee-resume.pdf", mime_type: null, byte_size: null, content_hash: "sha256-aaa", parser_version: "pdf-parser-v3", file_type: "pdf" as const, analysis_status: "succeeded" as const, created_at: "2026-01-01T00:00:00.000Z", updated_at: "x" },
      { id: "doc-2", profile_id: "profile-1", storage_bucket: "b", storage_path: "p2", original_file_name: "jordan-lee-resume-v2.docx", mime_type: null, byte_size: null, content_hash: "sha256-bbb", parser_version: "docx-parser-v1", file_type: "docx" as const, analysis_status: "succeeded" as const, created_at: "2026-01-05T00:00:00.000Z", updated_at: "x" },
    ],
    latestVersion: { id: "version-1", profile_id: "profile-1", source_document_id: "doc-2", parent_version_id: null, reason: "initial" as const, snapshot: resume as any, schema_version: "resume-structured-v1", serializer_version: "career-memory-runtime-v1", created_at: "2026-01-01T00:05:00.000Z", updated_at: "x" },
    experiences: [],
    languages: [],
    projects: [],
    credentials: [],
    awards: [],
    publications: [],
    tailoredResumes: [{ id: "tr-1", profile_id: "profile-1", application_id: null, resume_version_id: "version-1", overlay: runtimeToCareerTailoredResumeInsertInput("profile-1", runtime.overlayState.history[0]).overlay, template_id: null, ai_model: null, prompt_version: null, created_at: "2026-01-06T00:00:00.000Z", updated_at: "x" }],
  };
  const reconstructed = careerProfileToCanonicalRuntime(bundle);
  check("bundle->runtime: resume round-trips via snapshot", reconstructed.resume, resume);
  check("bundle->runtime: sourceDocuments ordered by created_at", reconstructed.sourceDocuments.map((d) => d.id), ["doc-1", "doc-2"]);
  check("bundle->runtime: metadata.parserVersion DERIVED from the linked source document", reconstructed.metadata.parserVersion, "docx-parser-v1");
  check("bundle->runtime: version.id preserved", reconstructed.version.id, "version-1");
  check("bundle->runtime: overlayState.history has 1 record", reconstructed.overlayState.history.length, 1);
  check("bundle->runtime: overlayState.history[0].appliedEntryIds preserved", reconstructed.overlayState.history[0].appliedEntryIds, ["exp-acme-ops"]);
}

// ==================== 28. Extended identity field coverage ====================
{
  const extendedResume = buildFixtureResume();
  extendedResume.identity = {
    ...extendedResume.identity,
    otherContactLines: extendedResume.identity?.otherContactLines ?? [],
    phone: { value: "+1 (514) 555-0182", confidence: 0.85, extractionMethod: "pattern-rule", source: trace("sec-identity", ["blk-99"]) },
    linkedin: { value: "linkedin.com/in/jordanlee", confidence: 0.75, extractionMethod: "pattern-rule", source: trace("sec-identity", ["blk-100"]) },
    portfolio: { value: "jordanlee.dev", confidence: 0.6, extractionMethod: "context-rule", source: trace("sec-identity", ["blk-101"]) },
  };
  const extendedRuntime = { ...runtime, resume: extendedResume };
  const insertInput = runtimeToCareerProfileInsertInput("user-1", extendedRuntime);
  check("profile insert: identity.phone preserved (jsonb, full StructuredTextValue)", (insertInput.identity as any).phone.value, "+1 (514) 555-0182");
  check("profile insert: identity.linkedin preserved", (insertInput.identity as any).linkedin.value, "linkedin.com/in/jordanlee");
  check("profile insert: identity.portfolio preserved", (insertInput.identity as any).portfolio.value, "jordanlee.dev");
  check("profile insert: identity.portfolio confidence preserved", (insertInput.identity as any).portfolio.confidence, 0.6);
}

// ==================== 29. Education extended fields (snapshot-only) ====================
{
  const snapshot = runtimeToCareerResumeVersionInsertInput("profile-1", runtime).snapshot as any;
  const edu = snapshot.education[0];
  check("education snapshot: fieldsOfStudy[0] preserved", edu.fieldsOfStudy[0].value, "Operations Management");
  check("education snapshot: credentials[] has 2 entries (double-credential composite line)", edu.credentials.length, 2);
  check("education snapshot: credentials[1] (Minor) preserved", edu.credentials[1].value, "Minor in Statistics");
  check("education snapshot: institutions[0] preserved", edu.institutions[0].value, "McGill University");
  check("education snapshot: honors[0] preserved", edu.honors[0].value, "Dean's List");
  check("education snapshot: honors[0] extractionMethod fallback preserved verbatim", edu.honors[0].extractionMethod, "fallback");
  check("education snapshot: dateRangeText preserved", edu.dateRangeText.value, "2013 – 2017");
}

// ==================== 30. Overlay with real rejections stored ====================
{
  const badRuntime = buildFixtureRuntime();
  const overlayWithRejection = { schemaVersion: "resume-structured-v1", entries: [{ entryId: "no-such-entry", bullets: [{ text: "x" }] }] };
  const applied = applyOverlay(badRuntime, overlayWithRejection);
  const insertInput = runtimeToCareerTailoredResumeInsertInput("profile-1", applied.runtime.overlayState.history[applied.runtime.overlayState.history.length - 1]);
  check("tailored resume insert: rejections[] preserved when an overlay entry is rejected", (insertInput.overlay as any).rejections.length, 1);
  check("tailored resume insert: rejection reason preserved", (insertInput.overlay as any).rejections[0].reason, "unknown-entry-id");
  check("tailored resume insert: rejection entryId preserved", (insertInput.overlay as any).rejections[0].entryId, "no-such-entry");

  const row = { id: "tr-x", profile_id: "profile-1", application_id: null, resume_version_id: null, overlay: insertInput.overlay, template_id: null, ai_model: null, prompt_version: null, created_at: "x", updated_at: "x" };
  const reconstructed = careerTailoredResumeRowToOverlayRecord(row);
  check("tailored resume row->record: rejections round-trip with reason", reconstructed.rejections[0].reason, "unknown-entry-id");
  check("tailored resume row->record: rejections round-trip with detail text", reconstructed.rejections[0].detail.length > 0, true);
}

// ==================== 31. Generated document metadata (DOCX variant) ====================
{
  const insertInput = mapGeneratedDocumentToInsertInput("tr-2", { storageBucket: "generated-resumes", storagePath: "profile-1/tr-2/resume.docx", fileType: "docx" });
  check("generated document insert (docx): file_type preserved", insertInput.file_type, "docx");
  check("generated document insert (docx): storage_bucket preserved", insertInput.storage_bucket, "generated-resumes");
}

// ==================== 32. Language DTO with null proficiency ====================
{
  const insertInput = runtimeToCareerLanguageInsertInput("profile-1", { name: "Spanish" }, 2);
  check("language insert: proficiency defaults to null when omitted", insertInput.proficiency, null);
  check("language insert: sort_order preserved", insertInput.sort_order, 2);
  const row = { id: "lang-2", profile_id: "profile-1", name: "Spanish", proficiency: null, sort_order: 2, created_at: "x", updated_at: "x" };
  const dto = careerLanguageRowToRuntime(row);
  check("language row->dto: null proficiency round-trips as null (not undefined, not empty string)", dto.proficiency, null);
}

// ==================== 33. Second credential/award full field coverage ====================
{
  const cred2 = resume.credentials[1];
  const insertInput = runtimeToCareerCredentialInsertInput("profile-1", cred2, { sourceDocumentId: null, sortOrder: 1 });
  check("credential insert (2nd): credential_id null when absent", insertInput.credential_id, null);
  check("credential insert (2nd): issuer null when absent", insertInput.issuer, null);
  check("credential insert (2nd): is_hidden defaults false", insertInput.is_hidden, false);

  const pub = resume.publications[0];
  check("publication: publisherOrVenue preserved via insert", runtimeToCareerPublicationInsertInput("profile-1", pub, { sourceDocumentId: null, sortOrder: 0 }).publisher_or_venue, "Canadian Logistics Review");
}

// ==================== 34. Sort/order helper functions ====================
{
  const rows = [
    { id: "b", sort_order: 1, created_at: "2026-01-01T00:00:01.000Z" },
    { id: "a", sort_order: 0, created_at: "2026-01-01T00:00:02.000Z" },
    { id: "c", sort_order: 0, created_at: "2026-01-01T00:00:00.000Z" },
  ];
  const sorted = bySortOrderThenCreatedAt(rows);
  check("bySortOrderThenCreatedAt: sorts by sort_order first, then created_at, then id", sorted.map((r) => r.id), ["c", "a", "b"]);

  const docs = [
    { id: "y", created_at: "2026-01-02T00:00:00.000Z" },
    { id: "x", created_at: "2026-01-01T00:00:00.000Z" },
  ];
  const sortedDocs = sortByCreatedAtThenId(docs);
  check("sortByCreatedAtThenId: sorts by created_at ascending", sortedDocs.map((d) => d.id), ["x", "y"]);
}

console.log(`\n--- ${pass} passed, ${fail} failed ---`);
if (fail > 0) process.exit(1);
