/*
  Phase 5D.4 - Production Readiness QA: 85-Pattern Gate for the Academic
  Composite Header Parser (Problem A: Double Degree/Double Major/Joint
  Program; Problem B: Inline Institution/Location Composite; Phase 5D.3D).

  This is a PERMANENT regression fixture, complementing (not replacing)
  multiLineHeaderFixtureGate.test.ts's own 62-pattern gate for the
  Phase 5D.3C base header shapes (Shapes A-L, Present/Current/Academic
  Year/Roman numeral/Bracket, Double Degree comma, Joint Program,
  Multiple Locations, Academic Honors, Dual Dates). Combined coverage:

    f14 (multiLineHeaderFixtureGate.test.ts) ... 62 patterns
    f15 (this file)                         ... 57 patterns (51 education
                                                 + 4 credential + 2 award)
    f16 (this file)                         ...  7 patterns (French /
                                                 English-French, disclosed
                                                 as a KNOWN LIMITATION, not
                                                 a passing feature - see
                                                 below)
    -----------------------------------------------------------
    total                                   ... 126 patterns, exceeding
                                                 the round's 85 minimum

  Every expected value below was HAND-AUTHORED against the fixture's own
  documented design intent (fixtures/scripts/generatePhase5D3DSyntheticFixtures.mts's
  own per-entry comments) and the parser's actual, understood decision
  rules (DEGREE_KEYWORD_RE / INSTITUTION_KEYWORD_RE / splitMultiValueSegment
  / parseInlineCompositeHeader) - each value was independently reasoned
  about, not generated by running the parser and echoing whatever it
  produced. Where investigation during Phase 5D.3D found the parser's
  actual behavior did not yet match the fixture's intent, the underlying
  bug was fixed at that time (see that phase's own commit) and these
  values reflect the CORRECTED, verified-by-hand behavior.

  French/English-French (f16): a real, disclosed LIMITATION, not a
  supported shape. DEGREE_KEYWORD_RE and INSTITUTION_KEYWORD_RE are
  English-keyword-only regexes, and sectionParser.ts's own heading
  classifier does not recognize "Formation" as an Education heading -
  see the KNOWN_LIMITATION assertions at the bottom of this file, which
  PIN the current (unsupported) behavior so a future accidental
  regression in either direction (silently "fixing" itself without an
  explicit round doing so, or getting worse) is caught. This file does
  NOT assert full French structuring correctness, because the engine
  does not currently provide it.

  Run with `npx tsx lib/documentPreservation/resumeStructured/academicCompositeFixtureGate.test.ts`.
*/
import fs from "node:fs";
import path from "node:path";
import { analyzeDocument } from "../layoutAnalysis";
import { closeSharedBrowser } from "../sharedBrowser";
import { buildLosslessResumeDocument } from "../losslessSemantic/buildLosslessDocument";
import { extractEducationEntries } from "./educationExtractor";
import { extractCredentialEntries } from "./credentialExtractor";
import { extractAwardEntries } from "./awardExtractor";
import type { EducationEntry, CredentialEntry, AwardEntry } from "./types";

let pass = 0;
let fail = 0;

function check(label: string, actual: unknown, expected: unknown) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  console.log(ok ? "PASS" : "FAIL", label, ok ? "" : `expected=${JSON.stringify(expected)} actual=${JSON.stringify(actual)}`);
  if (ok) pass++;
  else fail++;
}
function checkTrue(label: string, actual: boolean) {
  check(label, actual, true);
}

const FIXTURES_DIR = path.resolve(__dirname, "../../../fixtures/resumes/lossless-synthetic");

type EduExpect = { institutions: string[]; credentials: string[]; fieldsOfStudy: string[]; location?: string; date?: string };
type CredExpect = { names: string[]; issuer?: string; location?: string };
type AwardExpect = { names: string[]; issuer?: string };

// --- f15-academic-composite: 51 hand-authored Education expectations, in fixture order ---
const F15_EDUCATION: EduExpect[] = [
  { institutions: ["Example University"], credentials: ["B.Sc.", "M.Sc"], fieldsOfStudy: [], date: "2015 - 2019" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], date: "2016 - 2020" },
  { institutions: ["Example University"], credentials: ["B.A.", "B.Sc"], fieldsOfStudy: [], date: "2014 - 2018" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], date: "2017 - 2021" },
  { institutions: ["Example University"], credentials: ["B.Comm."], fieldsOfStudy: [], date: "2013 - 2018" },
  { institutions: ["Example Institute"], credentials: ["Diploma", "Certificate"], fieldsOfStudy: [], date: "2013 - 2015" },
  { institutions: ["Example University"], credentials: ["Bachelor of Arts", "Master of Arts"], fieldsOfStudy: ["History", "History"], date: "2010 - 2016" },
  { institutions: ["Example College", "Example Institute"], credentials: ["Bachelor of Science"], fieldsOfStudy: [], date: "2018 - 2022" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], date: "2019 - 2023" },
  { institutions: ["Example University"], credentials: ["Bachelor of Science", "Certificate"], fieldsOfStudy: ["Data Analytics"], date: "2015 - 2019" },
  { institutions: ["Example College"], credentials: ["Bachelor of Arts", "Diploma"], fieldsOfStudy: ["Public Relations"], date: "2012 - 2016" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], date: "2016 - 2020" },
  { institutions: ["Example Institute"], credentials: ["Bachelor of Engineering", "Diploma"], fieldsOfStudy: ["Management"], date: "2014 - 2019" },
  { institutions: ["Example University"], credentials: ["Bachelor of Arts"], fieldsOfStudy: ["Economics", "Political Science"], date: "2013 - 2017" },
  { institutions: ["Example College"], credentials: ["Bachelor of Science"], fieldsOfStudy: ["Biology and Chemistry"], date: "2015 - 2019" },
  { institutions: ["Example University"], credentials: ["Bachelor of Arts"], fieldsOfStudy: ["History & Philosophy"], date: "2012 - 2016" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], date: "2011 - 2015" },
  { institutions: ["Example University"], credentials: ["Bachelor of Science"], fieldsOfStudy: ["Major: Chemistry", "Minor: Biology"], date: "2014 - 2018" },
  { institutions: ["Example University"], credentials: ["Bachelor of Business Administration"], fieldsOfStudy: ["Concentration in Finance"], date: "2016 - 2020" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Toronto, ON", date: "2015 - 2019" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Vancouver, BC", date: "2014 - 2018" },
  { institutions: ["Example College"], credentials: [], fieldsOfStudy: [], location: "Ottawa, ON", date: "2013 - 2017" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Remote", date: "2020 - 2022" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Regina, SK", date: "2012 - 2016" },
  { institutions: ["Example College"], credentials: [], fieldsOfStudy: [], location: "Halifax, NS", date: "2011 - 2015" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Winnipeg, MB", date: "2010 - 2014" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Montreal, QC", date: "2017 - 2021" },
  { institutions: ["Example College"], credentials: [], fieldsOfStudy: [], location: "Calgary, AB", date: "2016 - 2020" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Toronto, ON", date: "2015 - 2019" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Vancouver, BC", date: "2014 - 2018" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Ottawa, ON", date: "2013 - 2017" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Vancouver, BC", date: "2012 - 2016" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Paris, France", date: "2015 - 2019" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Remote", date: "2021 - 2023" },
  { institutions: ["Example College"], credentials: [], fieldsOfStudy: [], location: "Hybrid", date: "2020 - 2022" },
  { institutions: ["Example University"], credentials: [], fieldsOfStudy: [], location: "Remote, Canada", date: "2019 - 2021" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Toronto, ON and Vancouver, BC", date: "2016 - 2020" },
  // Real-bug regression anchor: "Institution, Sub-unit" must stay ONE
  // institution string, never split, never treat the sub-unit as a location.
  { institutions: ["Example University, School of Business"], credentials: ["Master of Business Administration"], fieldsOfStudy: [], date: "2018 - 2020" },
  { institutions: ["Example University"], credentials: ["Bachelor of Science"], fieldsOfStudy: ["Research & Development"], date: "2015 - 2019" },
  { institutions: ["Example College"], credentials: ["Bachelor of Business Administration"], fieldsOfStudy: ["Sales and Marketing"], date: "2014 - 2018" },
  { institutions: ["Example Institute"], credentials: ["Bachelor of Science"], fieldsOfStudy: ["Health & Safety"], date: "2013 - 2017" },
  { institutions: ["Example University"], credentials: ["Bachelor of Arts"], fieldsOfStudy: ["Arts and Science Faculty"], date: "2012 - 2016" },
  { institutions: ["Example College"], credentials: ["Bachelor of Commerce"], fieldsOfStudy: ["Business/Technology Division"], date: "2011 - 2015" },
  { institutions: ["Example University"], credentials: ["Bachelor of Commerce"], fieldsOfStudy: ["Strategy, Operations, and Finance"], date: "2017 - 2021" },
  { institutions: ["Example Institute"], credentials: ["Bachelor of Engineering"], fieldsOfStudy: ["Oil & Gas"], date: "2016 - 2020" },
  { institutions: ["Example University"], credentials: ["Bachelor of Science"], fieldsOfStudy: ["Design and Development"], date: "2015 - 2019" },
  { institutions: ["Example University"], credentials: ["B.Sc.", "M.Sc"], fieldsOfStudy: [], location: "Toronto, ON", date: "2015 - 2020" },
  { institutions: ["Example Institute"], credentials: ["Bachelor of Arts"], fieldsOfStudy: ["Economics and Sociology"], location: "Vancouver, BC", date: "2014 - 2018" },
  { institutions: ["Example College", "Example University"], credentials: ["Bachelor of Arts"], fieldsOfStudy: [], date: "2018 - 2022" },
  { institutions: ["Example University"], credentials: ["B.Sc.", "B.A"], fieldsOfStudy: [], date: "2026" },
  { institutions: ["Example Institute"], credentials: [], fieldsOfStudy: [], location: "Hybrid", date: "2022 - Present" },
];

const F15_CREDENTIALS: CredExpect[] = [
  { names: ["Certified Financial Planner", "Certified Investment Manager"], issuer: "Financial Standards Board" },
  { names: ["Certified Scrum Master", "Certified Product Owner"] },
  { names: ["Project Management Professional"], issuer: "Project Management Institute", location: "Toronto, ON" },
  { names: ["Certified Health and Safety Officer"], issuer: "Workplace Standards Authority" },
];

const F15_AWARDS: AwardExpect[] = [
  { names: ["Excellence Award", "Innovation Award"], issuer: "Industry Recognition Council" },
  { names: ["Research and Development Award"], issuer: "Science Innovation Board" },
];

async function runF15() {
  const fileName = "f15-academic-composite.docx";
  const buffer = fs.readFileSync(path.join(FIXTURES_DIR, fileName));
  const layoutResult = await analyzeDocument("resume", "docx", buffer);
  const doc = buildLosslessResumeDocument(layoutResult, { fileName, fileType: "docx" });

  const eduSection = doc.sections.find((s) => s.normalizedType === "education");
  checkTrue(`${fileName}: has an education section`, eduSection !== undefined);
  if (eduSection) {
    const entries: EducationEntry[] = extractEducationEntries(eduSection.id, eduSection.blocks.filter((b) => b.blockType !== "heading"));
    check(`${fileName}: ${F15_EDUCATION.length} education entries detected`, entries.length, F15_EDUCATION.length);
    F15_EDUCATION.forEach((exp, i) => {
      const e = entries[i];
      if (!e) {
        fail++;
        console.log("FAIL", `${fileName}: education[${i}] missing entirely`);
        return;
      }
      check(`${fileName}: education[${i}] institutions`, e.institutions.map((x) => x.value), exp.institutions);
      check(`${fileName}: education[${i}] credentials`, e.credentials.map((x) => x.value), exp.credentials);
      check(`${fileName}: education[${i}] fieldsOfStudy`, e.fieldsOfStudy.map((x) => x.value), exp.fieldsOfStudy);
      check(`${fileName}: education[${i}] location`, e.location?.value, exp.location);
      check(`${fileName}: education[${i}] date`, e.dateRangeText?.value, exp.date);
      checkTrue(`${fileName}: education[${i}] rawHeaderText preserved`, e.rawHeaderText.length > 0);
      checkTrue(`${fileName}: education[${i}] traces back to real blocks`, e.source.sourceBlockIds.length > 0);
      // Backward-compat invariant: singular fields always equal array[0].
      check(`${fileName}: education[${i}] singular institution === institutions[0]`, e.institution?.value, e.institutions[0]?.value);
      check(`${fileName}: education[${i}] singular credential === credentials[0]`, e.credential?.value, e.credentials[0]?.value);
      check(`${fileName}: education[${i}] singular fieldOfStudy === fieldsOfStudy[0]`, e.fieldOfStudy?.value, e.fieldsOfStudy[0]?.value);
    });
  }

  const credSection = doc.sections.find((s) => s.normalizedType === "certifications" || s.normalizedType === "licenses");
  checkTrue(`${fileName}: has a certifications section`, credSection !== undefined);
  if (credSection) {
    const entries: CredentialEntry[] = extractCredentialEntries(credSection.id, credSection.blocks.filter((b) => b.blockType !== "heading"));
    check(`${fileName}: ${F15_CREDENTIALS.length} credential entries detected`, entries.length, F15_CREDENTIALS.length);
    F15_CREDENTIALS.forEach((exp, i) => {
      const e = entries[i];
      if (!e) {
        fail++;
        console.log("FAIL", `${fileName}: credential[${i}] missing entirely`);
        return;
      }
      check(`${fileName}: credential[${i}] names`, e.names.map((x) => x.value), exp.names);
      check(`${fileName}: credential[${i}] issuer`, e.issuer?.value, exp.issuer);
      check(`${fileName}: credential[${i}] location`, e.location?.value, exp.location);
      check(`${fileName}: credential[${i}] singular name === names[0]`, e.name?.value, e.names[0]?.value);
    });
  }

  const awardSection = doc.sections.find((s) => s.normalizedType === "awards");
  checkTrue(`${fileName}: has an awards section`, awardSection !== undefined);
  if (awardSection) {
    const entries: AwardEntry[] = extractAwardEntries(awardSection.id, awardSection.blocks.filter((b) => b.blockType !== "heading"));
    check(`${fileName}: ${F15_AWARDS.length} award entries detected`, entries.length, F15_AWARDS.length);
    F15_AWARDS.forEach((exp, i) => {
      const e = entries[i];
      if (!e) {
        fail++;
        console.log("FAIL", `${fileName}: award[${i}] missing entirely`);
        return;
      }
      check(`${fileName}: award[${i}] names`, e.names.map((x) => x.value), exp.names);
      check(`${fileName}: award[${i}] issuer`, e.issuer?.value, exp.issuer);
      check(`${fileName}: award[${i}] singular name === names[0]`, e.name?.value, e.names[0]?.value);
    });
  }
}

/*
  f16-french-academic - KNOWN LIMITATION pin, not a supported-shape gate.
  See this file's own header comment. Investigated during Phase 5D.4:
  (1) sectionParser.ts's heading classifier does not recognize "Formation"
  as an Education heading - it stays `normalizedType: "custom"`, so in
  the real pipeline this section's content is NEVER routed through
  extractEducationEntries at all (structured education fields for a
  French-headed section are lost entirely, not merely mis-structured).
  (2) Even when extractEducationEntries is invoked directly on the
  section's blocks (bypassing the classifier, as this test does to
  demonstrate the SECOND, independent gap), window-boundary and field
  assignment for French-only lines is unreliable, because
  DEGREE_KEYWORD_RE/INSTITUTION_KEYWORD_RE have no French vocabulary -
  a bare "Université ..." or "Baccalauréat ..." line matches neither
  list, so the multi-value/positional-fallback logic behaves
  inconsistently line-to-line rather than cleanly failing shut. This
  test does NOT assert specific per-entry field values for that reason
  - doing so would either (a) overfit to today's incidental fallback
  ordering (which could shift for unrelated reasons having nothing to
  do with French support), or (b) imply a level of French support that
  does not exist. It asserts only the two real, load-bearing findings:
  the section misclassification, and that raw text is never silently
  dropped even when structuring fails.
*/
async function runF16KnownLimitation() {
  const fileName = "f16-french-academic.docx";
  const buffer = fs.readFileSync(path.join(FIXTURES_DIR, fileName));
  const layoutResult = await analyzeDocument("resume", "docx", buffer);
  const doc = buildLosslessResumeDocument(layoutResult, { fileName, fileType: "docx" });

  const formationSection = doc.sections.find((s) => (s.originalHeading ?? "").trim() === "Formation");
  checkTrue(`${fileName}: KNOWN LIMITATION - "Formation" section exists in Phase 1 output`, formationSection !== undefined);
  checkTrue(
    `${fileName}: KNOWN LIMITATION - French heading "Formation" is NOT recognized as an education section (normalizedType stays "custom")`,
    formationSection !== undefined && formationSection.normalizedType !== "education"
  );

  if (formationSection) {
    const entries: EducationEntry[] = extractEducationEntries(formationSection.id, formationSection.blocks.filter((b) => b.blockType !== "heading"));
    checkTrue(`${fileName}: at least 1 entry recovered when extractor is invoked directly (bypassing the misclassified section)`, entries.length >= 1);
    let allRawPreserved = true;
    let allTraced = true;
    for (const e of entries) {
      if (e.rawHeaderText.length === 0) allRawPreserved = false;
      if (e.source.sourceBlockIds.length === 0) allTraced = false;
    }
    checkTrue(`${fileName}: no-data-loss contract holds even when field structuring for French text is unreliable (rawHeaderText)`, allRawPreserved);
    checkTrue(`${fileName}: no-data-loss contract holds even when field structuring for French text is unreliable (source trace)`, allTraced);
  }
}

/*
  PDF cross-format spot-check: full per-entry duplication of F15_EDUCATION/
  F15_CREDENTIALS/F15_AWARDS against the PDF variant is intentionally NOT
  done here (that already-heavy duplication buys little beyond what the
  DOCX pass above proves, since both formats normalize through the same
  LosslessSemantic representation) - instead this confirms the PDF path
  reaches the SAME entry counts and the SAME first/last education entry's
  key fields, which is enough to catch a PDF-specific extraction
  regression without doubling this file's size.
*/
async function runF15PdfSpotCheck() {
  const fileName = "f15-academic-composite.pdf";
  const buffer = fs.readFileSync(path.join(FIXTURES_DIR, fileName));
  const layoutResult = await analyzeDocument("resume", "pdf", buffer);
  const doc = buildLosslessResumeDocument(layoutResult, { fileName, fileType: "pdf" });

  const eduSection = doc.sections.find((s) => s.normalizedType === "education");
  checkTrue(`${fileName}: has an education section`, eduSection !== undefined);
  if (eduSection) {
    const entries = extractEducationEntries(eduSection.id, eduSection.blocks.filter((b) => b.blockType !== "heading"));
    check(`${fileName}: ${F15_EDUCATION.length} education entries detected (PDF/DOCX parity)`, entries.length, F15_EDUCATION.length);
    const first = entries[0];
    const last = entries[F15_EDUCATION.length - 1];
    check(`${fileName}: education[0] credentials (PDF/DOCX parity)`, first?.credentials.map((x) => x.value), F15_EDUCATION[0].credentials);
    check(`${fileName}: education[last] institutions (PDF/DOCX parity)`, last?.institutions.map((x) => x.value), F15_EDUCATION[F15_EDUCATION.length - 1].institutions);
  }

  const credSection = doc.sections.find((s) => s.normalizedType === "certifications" || s.normalizedType === "licenses");
  if (credSection) {
    const entries = extractCredentialEntries(credSection.id, credSection.blocks.filter((b) => b.blockType !== "heading"));
    check(`${fileName}: ${F15_CREDENTIALS.length} credential entries detected (PDF/DOCX parity)`, entries.length, F15_CREDENTIALS.length);
  }

  const awardSection = doc.sections.find((s) => s.normalizedType === "awards");
  if (awardSection) {
    const entries = extractAwardEntries(awardSection.id, awardSection.blocks.filter((b) => b.blockType !== "heading"));
    check(`${fileName}: ${F15_AWARDS.length} award entries detected (PDF/DOCX parity)`, entries.length, F15_AWARDS.length);
  }
}

async function main() {
  await runF15();
  await runF15PdfSpotCheck();
  await runF16KnownLimitation();
  await closeSharedBrowser();
  console.log(`\n--- ${pass} passed, ${fail} failed ---`);
  if (fail > 0) process.exit(1);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
