"use client";

/*
  Phase 6F - dev-only single-template preview page. HTML Preview via
  an iframe pointed at the real preview API route (never a mock);
  PDF/DOCX buttons hit the same route with a different ?format= and
  let the browser download the real generated bytes.
*/
import { useParams } from "next/navigation";
import { useState } from "react";
import { PageShell, Card } from "../../_components/shared";

const PAPER_SIZES = ["letter", "a4"] as const;

export default function TemplatePreviewPage() {
  const params = useParams<{ templateId: string }>();
  const templateId = params.templateId;
  const [paperSize, setPaperSize] = useState<(typeof PAPER_SIZES)[number]>("letter");

  const previewUrl = `/api/internal/canonical-career-memory/templates/${templateId}/preview?format=html&paperSize=${paperSize}`;
  const pdfUrl = `/api/internal/canonical-career-memory/templates/${templateId}/preview?format=pdf&paperSize=${paperSize}`;
  const docxUrl = `/api/internal/canonical-career-memory/templates/${templateId}/preview?format=docx&paperSize=${paperSize}`;

  return (
    <PageShell title={`Preview — ${templateId}`} description="Rendered from the synthetic Jordan Ellis fixture through the real Template Registry/Engine pipeline.">
      <Card className="mb-4">
        <div className="flex flex-wrap items-center gap-3">
          <label className="text-sm text-neutral-600">
            Paper size:{" "}
            <select value={paperSize} onChange={(e) => setPaperSize(e.target.value as (typeof PAPER_SIZES)[number])} className="rounded border border-neutral-300 px-2 py-1 text-sm">
              {PAPER_SIZES.map((size) => (
                <option key={size} value={size}>
                  {size}
                </option>
              ))}
            </select>
          </label>
          <a href={pdfUrl} target="_blank" rel="noreferrer" className="rounded-md bg-neutral-900 px-3 py-1.5 text-sm text-white hover:bg-neutral-800">
            Open PDF
          </a>
          <a href={docxUrl} className="rounded-md border border-neutral-300 px-3 py-1.5 text-sm text-neutral-700 hover:bg-neutral-50">
            Download DOCX
          </a>
        </div>
      </Card>
      <div className="overflow-hidden rounded-lg border border-neutral-200">
        <iframe src={previewUrl} title={`${templateId} HTML preview`} className="h-[1200px] w-full" />
      </div>
    </PageShell>
  );
}
